<a href="https://colab.research.google.com/github/sfwtopoulos/stocks/blob/master/Stocks_seq_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install talos

In [0]:
!pip install talos -q

In [6]:
pip install wget

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import math
import warnings
import numpy as np
import time
import sys

import pandas_datareader as pdr
#%tensorflow_version 2.x
# Restart runtime using 'Runtime' -> 'Restart runtime...'
%tensorflow_version 1.x
import tensorflow as tf
import keras


# from keras.layers import LSTM
# from keras.models import Sequential
# from keras.layers.wrappers import TimeDistributed
# from keras.layers.wrappers import TimeDistributed
# from keras.layers.core import Dense, Activation, Dropout
# from keras.preprocessing.sequence import pad_sequences

from tensorflow.python.keras.layers import Dense, Activation, Dropout, Input
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import LSTM
from tensorflow.python.keras.layers.wrappers import TimeDistributed
from tensorflow.python.keras.layers.wrappers import TimeDistributed
from tensorflow.python.keras.preprocessing.sequence import pad_sequences


from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt

import os
import wget
from zipfile import ZipFile

warnings.filterwarnings('ignore',category=FutureWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [0]:
# from keras.optimizers import Adam, Nadam
# from keras.activations import softmax
# from keras.losses import categorical_crossentropy, logcosh
# from talos.utils import lr_normalizer
import talos
from tensorflow.python.keras.optimizers import Adam, Nadam
from tensorflow.python.keras.activations import softmax
from tensorflow.python.keras.losses import categorical_crossentropy, logcosh
from talos.utils import lr_normalizer

Using TensorFlow backend.


In [0]:
print(keras.__version__)
print(tf.__version__)
#print(tensorflow.compat.v2.__version__)

2.3.0
1.14.0


In [0]:
#Small Dataset
#Data import from git repo
url = 'https://raw.githubusercontent.com/sfwtopoulos/stocks/master/stocks_dataset/combined.csv'
#df1 = pd.read_csv(url, error_bad_lines=False)
dfstocks = pd.read_csv(url, sep=',')

In [58]:
#Large Dataset
url = 'https://raw.githubusercontent.com/sfwtopoulos/stocks/master/stocks_dataset/combined_large.zip'
wget.download(url, '.')
# Create a ZipFile Object and load sample.zip in it
with ZipFile('combined_large.zip', 'r') as zipObj:
  # Extract all the contents of zip file in current directory
  zipObj.extractall()
os.listdir(".")

['.config',
 'combined_large (1).zip',
 '.ipynb_checkpoints',
 'combined_large.csv',
 'combined_large.zip',
 'sample_data']

In [0]:
dfstocks = pd.read_csv('combined_large.csv', sep=',') 

In [68]:
type(dfstocks['Date'])
dfstocks.dtypes



Date       object
Close      object
Volume     object
Open       object
High       object
Low        object
Company    object
dtype: object

In [0]:
dfstocks=dfstocks.head(10)

In [62]:
dfstocks

Date   Close/Last   Volume         Open         High          Low   AA
0  02-11-18  36.93000031  2681700           37  37.68999863  36.40999985   AA
1  01-11-18  36.77999878  2756200  35.43999863  36.88000107  35.24000168   AA
2  31-10-18  34.99000168  3380700  34.81999969  35.82099915  34.59999847   AA
3  30-10-18  34.15000153  2193400  33.65000153  34.47999954   33.4129982   AA
4  29-10-18  33.81999969  2219600  34.59999847  35.11999893  33.40000153   AA
5  26-10-18        34.25  3944700  33.84000015  34.99000168  33.08000183   AA
6  25-10-18  34.56000137  3200400  34.56000137  35.18999863  33.88000107   AA
7  24-10-18  34.20000076  4897200  37.11999893  37.34999847  34.04000092   AA
8  23-10-18  37.31999969  3192900  38.86999893  38.97000122  37.06999969   AA
9  22-10-18  39.45999908  3141100  38.72000122  39.75999832  38.63999939   AA

In [0]:
dfstocks=dfstocks[~dfstocks.Date.str.contains("nan")]
dfstocks=dfstocks[~dfstocks.Date.str.contains("Low")]
dfstocks=dfstocks[~dfstocks.Date.str.contains("N/A")]
dfstocks=dfstocks[~dfstocks.Date.str.contains("N/A")]
dfstocks.Date=pd.to_datetime(dfstocks.Date)

In [0]:
dfstocks['Date'] = dfstocks['Date'].dt.strftime('%Y-%m-%d')

In [66]:
dfstocks

Date   Close/Last   Volume         Open         High          Low   AA
0  2018-02-11  36.93000031  2681700           37  37.68999863  36.40999985   AA
1  2018-01-11  36.77999878  2756200  35.43999863  36.88000107  35.24000168   AA
2  2018-10-31  34.99000168  3380700  34.81999969  35.82099915  34.59999847   AA
3  2018-10-30  34.15000153  2193400  33.65000153  34.47999954   33.4129982   AA
4  2018-10-29  33.81999969  2219600  34.59999847  35.11999893  33.40000153   AA
5  2018-10-26        34.25  3944700  33.84000015  34.99000168  33.08000183   AA
6  2018-10-25  34.56000137  3200400  34.56000137  35.18999863  33.88000107   AA
7  2018-10-24  34.20000076  4897200  37.11999893  37.34999847  34.04000092   AA
8  2018-10-23  37.31999969  3192900  38.86999893  38.97000122  37.06999969   AA
9  2018-10-22  39.45999908  3141100  38.72000122  39.75999832  38.63999939   AA

In [67]:
#fix column names
dfstocks=dfstocks.rename({' AA':'Company', ' Close/Last':'Close', ' Volume':'Volume', ' Open':'Open', ' High':'High', ' Low':'Low'}, axis=1);
for col in dfstocks.columns: 
    print(col) 

Date
Close
Volume
Open
High
Low
Company


In [0]:
#drop $sign from values
dfstocks.Close=dfstocks['Close'].astype(str)
dfstocks.Close=dfstocks.Close.apply(lambda x: x.replace('$',''))
dfstocks.Open=dfstocks['Open'].astype(str)
dfstocks.Open=dfstocks.Open.apply(lambda x: x.replace('$',''))
dfstocks.High=dfstocks['High'].astype(str)
dfstocks.High=dfstocks.High.apply(lambda x: x.replace('$',''))
dfstocks.Low=dfstocks['Low'].astype(str)
dfstocks.Low=dfstocks.Low.apply(lambda x: x.replace('$',''))

In [70]:
#drop rows containing nan or header from the csv files
dfstocks=dfstocks[~dfstocks.Low.str.contains("nan")]
dfstocks=dfstocks[~dfstocks.Low.str.contains("Low")]
dfstocks=dfstocks[~dfstocks.Low.str.contains("N/A")]
dfstocks=dfstocks[~dfstocks.Volume.str.contains("N/A")]
dfstocks.reset_index(drop=True, inplace=True)
dfstocks.Date.count()

10

In [71]:
#sort dataframe based on date and Company Name
dfstocks = dfstocks.sort_values(['Date', 'Company'])
dfstocks.head(100)

Date        Close   Volume  ...         High          Low Company
1  2018-01-11  36.77999878  2756200  ...  36.88000107  35.24000168      AA
0  2018-02-11  36.93000031  2681700  ...  37.68999863  36.40999985      AA
9  2018-10-22  39.45999908  3141100  ...  39.75999832  38.63999939      AA
8  2018-10-23  37.31999969  3192900  ...  38.97000122  37.06999969      AA
7  2018-10-24  34.20000076  4897200  ...  37.34999847  34.04000092      AA
6  2018-10-25  34.56000137  3200400  ...  35.18999863  33.88000107      AA
5  2018-10-26        34.25  3944700  ...  34.99000168  33.08000183      AA
4  2018-10-29  33.81999969  2219600  ...  35.11999893  33.40000153      AA
3  2018-10-30  34.15000153  2193400  ...  34.47999954   33.4129982      AA
2  2018-10-31  34.99000168  3380700  ...  35.82099915  34.59999847      AA

[10 rows x 7 columns]

In [0]:
#Converting Datatypes
dfstocks.Date=pd.to_datetime(dfstocks.Date)
dfstocks.Close=pd.to_numeric(dfstocks.Close)
dfstocks.Volume=pd.to_numeric(dfstocks.Volume)
dfstocks.Open=pd.to_numeric(dfstocks.Open)
dfstocks.High=pd.to_numeric(dfstocks.High)
dfstocks.Low=pd.to_numeric(dfstocks.Low)
dfstocks.dtypes

Date       datetime64[ns]
Close             float64
Volume              int64
Open              float64
High              float64
Low               float64
Company            object
dtype: object

In [0]:
#dfstocks[dfstocks['Company'].str.contains("AMZN")]
sub_split=dfstocks[dfstocks['Company'].str.contains("MDLZ")]
sub_split.isnull().values.any()
sub_split.isna().values.any()
sub_split = sub_split.sort_values(['Date'])
sub_split.reset_index(drop=True, inplace=True)
sub_split.shape[0]

2487

In [0]:
sub_split

Date    Close    Volume     Open     High      Low Company
0    2010-02-16  19.3633  54149150  19.1695  19.3633  18.9288    MDLZ
1    2010-02-17  19.1360  24833350  19.2898  19.3499  19.0157    MDLZ
2    2010-02-18  19.2564  20606450  19.1494  19.2564  19.0324    MDLZ
3    2010-02-19  19.3299  15497250  19.2229  19.4168  19.1494    MDLZ
4    2010-02-22  19.3499  27292690  19.3098  19.4435  19.1494    MDLZ
...         ...      ...       ...      ...      ...      ...     ...
2482 2019-12-24  54.9900   1833763  54.9400  55.1800  54.7400    MDLZ
2483 2019-12-26  54.8500   3565549  54.9700  55.0741  54.7200    MDLZ
2484 2019-12-27  55.2800   4229449  54.9300  55.3300  54.8000    MDLZ
2485 2019-12-30  55.0000   3104187  54.9200  55.0700  54.5651    MDLZ
2486 2019-12-31  55.0800   5039525  55.0500  55.1400  54.7600    MDLZ

[2487 rows x 7 columns]

In [0]:
# prepare training and testing data sets for LSTM based sequence modeling
#def dimitris_function(time_series, scaling=True,split_ratio=0.9):
def dimitris_function(time_series,split_ratio=0.9):

    series1 = pd.Series(time_series[time_series.columns[0]])
    series2 = pd.Series(time_series[time_series.columns[1]])
    series3 = pd.Series(time_series[time_series.columns[2]])
    series4 = pd.Series(time_series[time_series.columns[3]])
    series5 = pd.Series(time_series[time_series.columns[4]])

    values1 = series1.values
    values1 = values1.reshape((len(values1), 1))
    values2 = series2.values
    values2 = values2.reshape((len(values2), 1))
    values3 = series3.values
    values3 = values3.reshape((len(values3), 1))
    values4 = series4.values
    values4 = values4.reshape((len(values4), 1))
    values5 = series5.values
    values5 = values5.reshape((len(values5), 1))

    #scaler2 --> Close Price Scaler
    scaler1 = MinMaxScaler(feature_range=(0, 1))
    time_series["scaled1"] = scaler1.fit_transform(values1)
    scaler2 = MinMaxScaler(feature_range=(0, 1))
    time_series["scaled2"]= scaler2.fit_transform(values2)
    scaler3 = MinMaxScaler(feature_range=(0, 1))
    time_series["scaled3"]= scaler3.fit_transform(values3)
    scaler4 = MinMaxScaler(feature_range=(0, 1))
    time_series["scaled4"]= scaler4.fit_transform(values4)
    scaler5 = MinMaxScaler(feature_range=(0, 1))
    time_series["scaled5"]= scaler5.fit_transform(values5)


    time_series = time_series[["scaled1","scaled2","scaled3","scaled4","scaled5"]].values

        
    split_ratio = int(len(time_series) * split_ratio)

    train = time_series[0:split_ratio]
    test = time_series[split_ratio:len(time_series)-1]
    
    # return train,test,scaler1,scaler2
    return train,test,scaler2


In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
#def get_seq_model(hidden_units1=40, hidden_units2=65, hidden_units3=32, drop=0.2,input_shape=(1,1)):
def get_seq_model(x_train, y_train, x_val, y_val, params):  

    # create and fit the LSTM network
    model = Sequential()

    # samples*timesteps*features
    # https://keras.io/getting-started/sequential-model-guide/
    #https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0227222

    ######!!!!!#####!!!!!
    #(train_x.shape[1],5) where 5 is the number of features is equal to :
    #(train_x.shape[1],train_x.shape[2])
    model.add(LSTM(
                   input_shape=(x_train.shape[1],x_train.shape[2]),
                   units = params['hidden_1'],  
                   #activation='relu',recurrent_activation='sigmoid',
                   return_sequences=True
    ))
    model.add(Dropout(params['dropout']))
    model.add(LSTM(
                   units = params['hidden_2'],
                   #activation='relu',recurrent_activation='sigmoid',
                   return_sequences=True
    ))
    model.add(Dropout(params['dropout']))   
    model.add(LSTM(
                   units = params['hidden_3'], 
                   #activation='relu',recurrent_activation='sigmoid',
                   return_sequences=True
    ))
    model.add(Dropout(params['dropout']))

    # readout layer. TimeDistributedDense uses the same weights for all
    # time steps.
    # model.add(TimeDistributed(Dense(1))) #number of inputs in the 1st layer
   # model.add(TimeDistributed(Dense(5)))
    model.add(TimeDistributed(Dense(5)))
    start = time.time()
    
    model.compile(loss="mse", optimizer="rmsprop")
    timestr = time.strftime("%Y%m%d-%H%M%S")
    checkpoint_path = "/content/gdrive/My Drive/checkpoints1"  + "/cp-{epoch:04d}.ckpt"
    checkpoint_dir = os.path.dirname(checkpoint_path)
    cp_callback = tf.keras.callbacks.ModelCheckpoint(
        checkpoint_path, verbose=1, save_weights_only=True,#save_best_only='TRUE'
        # Save weights, every 5-epochs.
        period=15)
   # early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=40)
    
    out = model.fit(x_train, y_train,
              epochs=params['epochs'], batch_size=1,
              validation_data=[x_val, y_val],
              #epochs=200, batch_size=1,
              verbose=1,callbacks=[cp_callback])

    return out, model

In [0]:
#Parameters for the model
p = {'hidden_1':[40, 45],
     'hidden_2':[40, 45],
     'hidden_3':[40, 45],
     'dropout': (0.5, 0.6, 0.1),
     'epochs': [20, 30,100]
     }

In [0]:
# print(type(sub_split.Close))
sub_split_date=sub_split[['Date']]
sub_split=sub_split[['Volume', 'Close', 'Open', 'High', 'Low']]
#sub_split.columns[1]

In [0]:
# split train and test datasets
train,test,scaler_Close = dimitris_function(sub_split,split_ratio=0.7)

#train
print(len(train))
print(train.shape[0])
print(train.shape)
print(test.shape)
print(train)

1740
1740
(1740, 5)
(746, 5)
[[0.88815584 0.02021012 0.01335138 0.01636724 0.01466068]
 [0.39046289 0.01423411 0.01651313 0.01601441 0.01695744]
 [0.31870301 0.01739958 0.01282311 0.01355248 0.01739882]
 ...
 [0.07876951 0.68608191 0.69959394 0.69877535 0.69367717]
 [0.13961111 0.67241044 0.68067072 0.68508332 0.68019791]
 [0.10580105 0.69607261 0.66910654 0.69890701 0.68019791]]


In [0]:
#We use numpy to reshape our time series into 3D tensors.
train = np.reshape(train,(train.shape[0],1,5))
test = np.reshape(test,(test.shape[0],1,5))

train_x = train[:,:,:]
train_y = train[:,:,:]

test_x = test[:,:,:]
test_y = test[:,:,:]

print("Data Split Complete")

print("train_x shape={}".format(train_x.shape))
print("train_y shape={}".format(train_y.shape))
print("test_x shape={}".format(test_x.shape))
print("test_y shape={}".format(test_y.shape))

Data Split Complete
train_x shape=(1740, 1, 5)
train_y shape=(1740, 1, 5)
test_x shape=(746, 1, 5)
test_y shape=(746, 1, 5)


In [0]:
# x=np.concatenate((train_x, test_x), axis=1)
# y=np.concatenate((train_y, test_y), axis=1)
# print("x shape={}".format(x.shape))
# print("y shape={}".format(y.shape))
import talos


In [0]:
#####!!!!!#####!!!!!
#(train_x.shape[1],5) where 5 is the number of features is equal to :
train_x.shape[2]
 #,train_x.shape[2])
#input_shape=(train_x.shape[1],train_x.shape[2])
#input_shape.shape
#validation_data=[(test_x.shape[1],test_x.shape[2]), test_y]
#test=tuple(validation_data)

5

In [0]:
import sklearn

In [0]:
print('The scikit-learn version is {}.'.format(sklearn.__version__))
talos.Sca

The scikit-learn version is 0.22.2.post1.


In [0]:

scan_obj = talos.Scan(x=train_x,
                      y=train_y,
                      x_val=test_x,
                      #x_val=train_x,
                      y_val=test_y,
                     #y_val=train_y,

                      params=p,
                      val_split=0.1,
                      model=get_seq_model,
                      #shuffle=False,
                      experiment_name='gdrive/My Drive/test',
                      #fraction_limit=0.1
                      )


In [0]:
#from google.colab import drive
#drive.mount('/content/drive')

In [0]:
scan_obj.data.head()

In [0]:
train_y

In [0]:
# train the model
#https://medium.com/@rajath95/how-to-save-and-upload-deep-learning-machine-learning-models-in-google-colab-using-google-drive-eb2901937ae
# seq_lstm_model.fit(train_x, train_y,
#                 epochs=2, batch_size=1,
#                 #epochs=200, batch_size=1,
#                 verbose=1)
# print("Model Fit Complete")

In [0]:
# train fit performance
trainPredict = seq_lstm_model.predict(train_x)
trainScore = math.sqrt(mean_squared_error(train_y[0], trainPredict[0]))
print('Train Score: %.2f RMSE' % (trainScore))

In [0]:
print()

In [0]:
trainPredict

In [0]:
# Pad input sequence
testPredict = pad_sequences(test_x,maxlen=train_x.shape[1],padding='post',dtype='float64')

In [0]:
# forecast values
testPredict = seq_lstm_model.predict(testPredict)
testPredict

In [0]:
#Drop all other variables except Close Price Output
testPredict=np.delete(testPredict, [2,3,4], 2)
trainPredict=np.delete(trainPredict, [2,3,4], 2)
# testPredict=np.delete(testPredict, 3, 2)
# trainPredict=np.delete(trainPredict, 3, 2)
# testPredict=np.delete(testPredict, 4, 2)
# trainPredict=np.delete(trainPredict, 4, 2)
testPredict=np.delete(testPredict, 0, 2)
trainPredict=np.delete(trainPredict, 0, 2)

In [0]:
testPredict

In [0]:
trainPredict


In [0]:
type(testPredict)

In [0]:
# # inverse transformation of the Close Price
trainPredict = scaler_Close.inverse_transform(trainPredict.\
                                        reshape(-1,1))
testPredict = scaler_Close.inverse_transform(testPredict.\
                                       reshape(-1,1))

In [0]:
trainPredict

In [0]:
# plot the true and forecasted values
split_ratio = len(trainPredict)+1

plt.plot(sub_split_date.Date,
          sub_split.Close.values,c='black',
          alpha=0.3,label='True Data')

plt.plot(sub_split_date.Date[1:split_ratio],
          trainPredict,label='Training Fit',c='g')

plt.plot(sub_split_date.Date[split_ratio+1:],
          testPredict[:test_x.shape[1]],label='Testing Forecast')
plt.title('Forecast Plot')
plt.legend()
#plt.show()
plt.rcParams["figure.figsize"] = (20,10)
plt.show()